# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ieHOn_GYWKvFxh6l-iV92NDxkw6fTzC
"""

# 1. Mount your Google Drive
from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.models import load_model

model           = load_model('/content/drive/MyDrive/efficientnetb0_brain_tumor.keras')
model_mobilenet = load_model('/content/drive/MyDrive/mobilenetv2_brain_tumor.keras')
model_resnet    = load_model('/content/drive/MyDrive/resnet50_brain_tumor.keras')

print("All 3 models loaded successfully!")

import json
import zipfile
import shutil

def fix_and_resave(model, save_path):
    model.save(save_path)

    with zipfile.ZipFile(save_path, 'r') as z:
        config = json.loads(z.read('config.json'))

    config_str = json.dumps(config)
    config_str = config_str.replace('"quantization_config": null,', '')
    config_str = config_str.replace(', "quantization_config": null', '')

    with zipfile.ZipFile(save_path, 'a') as z:
        z.writestr('config.json', config_str)

    print(f"Fixed and saved: {save_path}")

fix_and_resave(model,           'efficientnetb0_fixed.keras')
fix_and_resave(model_mobilenet, 'mobilenetv2_fixed.keras')
fix_and_resave(model_resnet,    'resnet50_fixed.keras')

shutil.copy('efficientnetb0_fixed.keras', '/content/drive/MyDrive/efficientnetb0_fixed.keras')
shutil.copy('mobilenetv2_fixed.keras',    '/content/drive/MyDrive/mobilenetv2_fixed.keras')
shutil.copy('resnet50_fixed.keras',       '/content/drive/MyDrive/resnet50_fixed.keras')

from google.colab import files
files.download('efficientnetb0_fixed.keras')
files.download('mobilenetv2_fixed.keras')
files.download('resnet50_fixed.keras')

print("Done!")

# 2. Copy the zip file to Colab's fast local environment
# (Note: If your file has a space in the name like "dataset (2).zip",
# we put it in quotes so Linux can read it correctly)
!cp "/content/drive/MyDrive/dataset (2).zip" /content/

# 3. Unzip it quietly into a local folder named 'my_dataset'
!unzip -q /content/"dataset (2).zip" -d /content/my_dataset

print("Setup complete! Your files are ready at: /content/my_dataset/")

import os
# List the contents inside your unzipped dataset folder
os.listdir('/content/my_dataset')

import os
# Look inside the nested dataset folder
os.listdir('/content/my_dataset/dataset')

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import (
    Dense, Dropout, GlobalAveragePooling2D, BatchNormalization
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
)
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score
)

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

TRAIN_DIR = '/content/my_dataset/dataset/train'
VALID_DIR = '/content/my_dataset/dataset/valid'
TEST_DIR  = '/content/my_dataset/dataset/test'

IMG_SIZE    = (224, 224)
BATCH_SIZE  = 32
NUM_CLASSES = 4
CLASSES     = ['glioma', 'meningioma', 'no_tumor', 'pituitary']

# Seeds for reproducibility
tf.random.set_seed(42)
np.random.seed(42)

print("Paths configured successfully.")

# EfficientNetB0 requires its own preprocess_input
# No augmentation needed — dataset is already augmented

train_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
valid_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
test_datagen  = ImageDataGenerator(preprocessing_function=preprocess_input)

train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

valid_generator = valid_datagen.flow_from_directory(
    VALID_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print("\nClass indices:", train_generator.class_indices)
print(f"Train samples  : {train_generator.samples}")
print(f"Valid samples  : {valid_generator.samples}")
print(f"Test  samples  : {test_generator.samples}")

def show_sample_images(generator, classes, n=8):
    images, labels = next(generator)
    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    fig.suptitle('Sample MRI Images from Training Set', fontsize=16, fontweight='bold')
    for i, ax in enumerate(axes.flat):
        if i >= n:
            break
        img = images[i]
        # Reverse preprocess for display
        img_display = (img - img.min()) / (img.max() - img.min())
        ax.imshow(img_display)
        ax.set_title(classes[np.argmax(labels[i])], fontsize=12, fontweight='bold')
        ax.axis('off')
    plt.tight_layout()
    plt.savefig('sample_images.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Sample images saved.")

show_sample_images(train_generator, CLASSES)

def build_efficientnetb0(num_classes=4):
    # Load EfficientNetB0 with ImageNet weights, remove top classifier
    base_model = EfficientNetB0(
        weights='imagenet',
        include_top=False,
        input_shape=(224, 224, 3)
    )

    # Freeze all base layers for Phase 1
    base_model.trainable = False

    # Build classification head
    x = base_model.output
    x = GlobalAveragePooling2D(name='gap')(x)
    x = BatchNormalization(name='bn')(x)
    x = Dense(256, activation='relu', name='dense_256')(x)
    x = Dropout(0.4, name='dropout')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions')(x)

    model = Model(inputs=base_model.input, outputs=outputs)
    return model, base_model

model, base_model = build_efficientnetb0(NUM_CLASSES)

print(f"Total layers      : {len(model.layers)}")
print(f"Trainable layers  : {len([l for l in model.layers if l.trainable])}")
print(f"Frozen layers     : {len([l for l in model.layers if not l.trainable])}")
model.summary()

print("\n" + "="*60)
print("  PHASE 1 — Training Classification Head (Base Frozen)")
print("="*60)

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase1 = [
    ModelCheckpoint(
        'best_phase1.h5',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-7,
        verbose=1
    )
]

history_phase1 = model.fit(
    train_generator,
    epochs=10,
    validation_data=valid_generator,
    callbacks=callbacks_phase1,
    verbose=1
)

print(f"\nPhase 1 best val accuracy: {max(history_phase1.history['val_accuracy']):.4f}")

print("\n" + "="*60)
print("  PHASE 2 — Fine-Tuning Last 30 Layers")
print("="*60)

# Unfreeze the last 30 layers of the base model
base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

trainable_now = len([l for l in model.layers if l.trainable])
print(f"Trainable layers now: {trainable_now}")

# Recompile with very low learning rate
model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase2 = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        'best_efficientnetb0.h5',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-8,
        verbose=1
    )
]

history_phase2 = model.fit(
    train_generator,
    epochs=20,
    validation_data=valid_generator,
    callbacks=callbacks_phase2,
    verbose=1
)

print(f"\nPhase 2 best val accuracy: {max(history_phase2.history['val_accuracy']):.4f}")

def plot_training_history(h1, h2):
    # Combine both phases
    acc     = h1.history['accuracy']     + h2.history['accuracy']
    val_acc = h1.history['val_accuracy'] + h2.history['val_accuracy']
    loss    = h1.history['loss']         + h2.history['loss']
    val_loss= h1.history['val_loss']     + h2.history['val_loss']
    epochs  = range(1, len(acc) + 1)
    phase1_end = len(h1.history['accuracy'])

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle('EfficientNetB0 — Training History', fontsize=16, fontweight='bold')

    # Accuracy
    axes[0].plot(epochs, acc,     'b-o', markersize=3, label='Train Accuracy')
    axes[0].plot(epochs, val_acc, 'r-o', markersize=3, label='Val Accuracy')
    axes[0].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[0].fill_betweenx([0, 1], 1, phase1_end, alpha=0.05, color='blue', label='Phase 1')
    axes[0].fill_betweenx([0, 1], phase1_end, len(epochs), alpha=0.05, color='green', label='Phase 2')
    axes[0].set_title('Accuracy', fontsize=13)
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[0].set_ylim([0, 1])

    # Loss
    axes[1].plot(epochs, loss,     'b-o', markersize=3, label='Train Loss')
    axes[1].plot(epochs, val_loss, 'r-o', markersize=3, label='Val Loss')
    axes[1].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[1].fill_betweenx([0, max(loss+val_loss)], 1, phase1_end, alpha=0.05, color='blue')
    axes[1].fill_betweenx([0, max(loss+val_loss)], phase1_end, len(epochs), alpha=0.05, color='green')
    axes[1].set_title('Loss', fontsize=13)
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('training_curves_efficientnetb0.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Training curves saved.")

plot_training_history(history_phase1, history_phase2)

print("\n" + "="*60)
print("  EVALUATING ON TEST SET")
print("="*60)

# Load best saved weights
model.load_weights('best_efficientnetb0.h5')

test_loss, test_accuracy = model.evaluate(test_generator, verbose=1)
print(f"\nTest Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")

# Get predictions
test_generator.reset()
y_pred_probs = model.predict(test_generator, verbose=1)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = test_generator.classes

# Map index to class name
class_names = list(test_generator.class_indices.keys())

print("\n" + "="*60)
print("  CLASSIFICATION REPORT")
print("="*60)
print(classification_report(y_true, y_pred, target_names=class_names))

def plot_confusion_matrix(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))
    fig.suptitle('EfficientNetB0 — Confusion Matrix', fontsize=16, fontweight='bold')

    # Raw counts
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[0])
    axes[0].set_title('Counts', fontsize=13)
    axes[0].set_xlabel('Predicted Label', fontsize=11)
    axes[0].set_ylabel('True Label', fontsize=11)

    # Percentage
    sns.heatmap(cm_percent, annot=True, fmt='.1f', cmap='Greens',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[1])
    axes[1].set_title('Percentage (%)', fontsize=13)
    axes[1].set_xlabel('Predicted Label', fontsize=11)
    axes[1].set_ylabel('True Label', fontsize=11)

    plt.tight_layout()
    plt.savefig('confusion_matrix_efficientnetb0.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Confusion matrix saved.")

plot_confusion_matrix(y_true, y_pred, class_names)

import random

class_names = [k for k, v in sorted(test_generator.class_indices.items(), key=lambda x: x[1])]
print("Correct class order:", class_names)

def visualize_predictions_balanced(generator, model, class_names, n_per_class=3):
    generator.reset()

    # Collect images per class
    class_images = {i: [] for i in range(len(class_names))}

    # Loop through batches until we have n_per_class for every class
    for images, labels in generator:
        for i in range(len(images)):
            label_idx = np.argmax(labels[i])
            if len(class_images[label_idx]) < n_per_class:
                class_images[label_idx].append((images[i], labels[i]))
        # Stop when all classes have enough images
        if all(len(v) >= n_per_class for v in class_images.values()):
            break

    # Flatten: 4 classes x 3 images = 12 images total
    all_samples = []
    for idx in range(len(class_names)):
        all_samples.extend(class_images[idx])

    fig, axes = plt.subplots(3, 4, figsize=(18, 12))
    fig.suptitle('EfficientNetB0 — Predictions on Test Images (Balanced)',
                 fontsize=16, fontweight='bold')

    for i, ax in enumerate(axes.flat):
        img, label = all_samples[i]

        # Predict
        pred = model.predict(np.expand_dims(img, axis=0), verbose=0)[0]
        true_label = class_names[np.argmax(label)]
        pred_label = class_names[np.argmax(pred)]
        confidence = np.max(pred) * 100
        correct = true_label == pred_label

        # Display
        img_display = (img - img.min()) / (img.max() - img.min())
        ax.imshow(img_display, cmap='gray')
        color = 'green' if correct else 'red'
        ax.set_title(
            f"True: {true_label}\nPred: {pred_label} ({confidence:.1f}%)",
            fontsize=9, color=color, fontweight='bold'
        )
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(3)
        ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)

    correct_patch = mpatches.Patch(color='green', label='Correct Prediction')
    wrong_patch   = mpatches.Patch(color='red',   label='Wrong Prediction')
    fig.legend(handles=[correct_patch, wrong_patch], loc='lower center',
               ncol=2, fontsize=11, bbox_to_anchor=(0.5, 0.01))

    plt.tight_layout(rect=[0, 0.04, 1, 1])
    plt.savefig('predictions_efficientnetb0.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Prediction visualization saved.")

visualize_predictions_balanced(test_generator, model, class_names, n_per_class=3)

print("\n" + "="*60)
print("  EFFICIENTNETB0 — FINAL RESULTS SUMMARY")
print("="*60)
print(f"  Test Accuracy  : {test_accuracy*100:.2f}%")
print(f"  Test Loss      : {test_loss:.4f}")
print(f"  Total Epochs   : {len(history_phase1.history['accuracy']) + len(history_phase2.history['accuracy'])}")
print(f"  Phase 1 Epochs : {len(history_phase1.history['accuracy'])}")
print(f"  Phase 2 Epochs : {len(history_phase2.history['accuracy'])}")
print(f"  Classes        : {class_names}")
print("="*60)

cm = confusion_matrix(y_true, y_pred)
per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100
for name, acc in zip(class_names, per_class_acc):
    print(f"  {name:<15}: {acc:.2f}%")
print("="*60)

# ─────────────────────────────────────────────
# CELL 14 — Save Model & Download
# ─────────────────────────────────────────────
import os
from google.colab import files

# Re-run per_class_accuracy plot to make sure the file exists
def plot_per_class_accuracy(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100

    colors = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0']
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.bar(class_names, per_class_acc, color=colors, edgecolor='white',
                  linewidth=1.5, width=0.5)

    for bar, acc in zip(bars, per_class_acc):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{acc:.2f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')

    ax.set_title('EfficientNetB0 — Per-Class Accuracy on Test Set',
                 fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Tumor Class', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_ylim([0, 110])
    ax.axhline(y=np.mean(per_class_acc), color='red', linestyle='--',
               alpha=0.7, label=f'Mean: {np.mean(per_class_acc):.2f}%')
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig('per_class_accuracy_efficientnetb0.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Per-class accuracy chart saved.")

plot_per_class_accuracy(y_true, y_pred, class_names)

# Save model in modern Keras format
model.save('efficientnetb0_brain_tumor.keras')
print("Model saved as: efficientnetb0_brain_tumor.keras")

model.save('/content/drive/MyDrive/efficientnetb0_brain_tumor.keras')
print("Model also saved to Google Drive.")

# Safe download
files_to_download = [
    'efficientnetb0_brain_tumor.keras',
    'training_curves_efficientnetb0.png',
    'confusion_matrix_efficientnetb0.png',
    'predictions_efficientnetb0.png',
    'per_class_accuracy_efficientnetb0.png',
    'sample_images.png'
]

for f in files_to_download:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
    else:
        print(f"SKIPPED (not found): {f}")

print("\nDone! Use efficientnetb0_brain_tumor.keras in your Flask app.")

# ─────────────────────────────────────────────
# CELL 15 — Predict Your Own Image
# ─────────────────────────────────────────────
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input
from google.colab import files

def predict_single_image(model, class_names):
    # Upload image from your computer
    print("Please upload an MRI image...")
    uploaded = files.upload()

    for img_name in uploaded.keys():
        # Load and preprocess the image
        img = image.load_img(img_name, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = preprocess_input(img_array)
        img_batch = np.expand_dims(img_array, axis=0)

        # Predict
        predictions = model.predict(img_batch, verbose=0)[0]
        pred_class  = class_names[np.argmax(predictions)]
        confidence  = np.max(predictions) * 100

        # Plot
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle('Brain Tumor Classification — EfficientNetB0',
                     fontsize=14, fontweight='bold')

        # Left — the MRI image
        img_display = image.load_img(img_name, target_size=(224, 224))
        axes[0].imshow(img_display)
        axes[0].set_title(f'Uploaded Image: {img_name}', fontsize=11)
        axes[0].axis('off')

        # Right — confidence bar chart for all classes
        colors = ['#4CAF50' if c == pred_class else '#B0BEC5' for c in class_names]
        bars = axes[1].barh(class_names, predictions * 100,
                            color=colors, edgecolor='white', height=0.5)

        for bar, prob in zip(bars, predictions * 100):
            axes[1].text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                         f'{prob:.2f}%', va='center', fontsize=11, fontweight='bold')

        axes[1].set_xlim([0, 115])
        axes[1].set_xlabel('Confidence (%)', fontsize=11)
        axes[1].set_title('Prediction Confidence per Class', fontsize=11)
        axes[1].spines['top'].set_visible(False)
        axes[1].spines['right'].set_visible(False)
        axes[1].grid(axis='x', alpha=0.3)

        # Result box
        result_color = '#4CAF50'
        fig.text(0.5, 0.01,
                 f'Prediction: {pred_class}   |   Confidence: {confidence:.2f}%',
                 ha='center', fontsize=13, fontweight='bold',
                 color='white',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor=result_color, alpha=0.9))

        plt.tight_layout(rect=[0, 0.06, 1, 1])
        plt.savefig(f'prediction_{img_name}', dpi=150, bbox_inches='tight')
        plt.show()

        # Print summary
        print("\n" + "="*50)
        print(f"  Image      : {img_name}")
        print(f"  Prediction : {pred_class}")
        print(f"  Confidence : {confidence:.2f}%")
        print("─"*50)
        for cls, prob in zip(class_names, predictions):
            marker = " ◄ PREDICTED" if cls == pred_class else ""
            print(f"  {cls:<15}: {prob*100:.2f}%{marker}")
        print("="*50)

predict_single_image(model, class_names)

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

def build_mobilenetv2(num_classes=4):
    base_model = MobileNetV2(
        weights='imagenet',
        include_top=False,
        input_shape=(224, 224, 3)
    )
    base_model.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D(name='gap_mobilenet')(x)
    x = BatchNormalization(name='bn_mobilenet')(x)
    x = Dense(256, activation='relu', name='dense_256_mobilenet')(x)
    x = Dropout(0.4, name='dropout_mobilenet')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions_mobilenet')(x)

    model_mobilenet = Model(inputs=base_model.input, outputs=outputs)
    return model_mobilenet, base_model

model_mobilenet, base_model_mobilenet = build_mobilenetv2(NUM_CLASSES)

print(f"Total layers      : {len(model_mobilenet.layers)}")
print(f"Trainable layers  : {len([l for l in model_mobilenet.layers if l.trainable])}")
print(f"Frozen layers     : {len([l for l in model_mobilenet.layers if not l.trainable])}")
model_mobilenet.summary()

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess

train_generator_mobilenet = ImageDataGenerator(preprocessing_function=mobilenet_preprocess).flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

valid_generator_mobilenet = ImageDataGenerator(preprocessing_function=mobilenet_preprocess).flow_from_directory(
    VALID_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_generator_mobilenet = ImageDataGenerator(preprocessing_function=mobilenet_preprocess).flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

class_names_mobilenet = [k for k, v in sorted(train_generator_mobilenet.class_indices.items(), key=lambda x: x[1])]

print("Class names:", class_names_mobilenet)
print(f"Train samples : {train_generator_mobilenet.samples}")
print(f"Valid samples : {valid_generator_mobilenet.samples}")
print(f"Test  samples : {test_generator_mobilenet.samples}")

print("="*60)
print("  PHASE 1 — Training Classification Head (Base Frozen)")
print("="*60)

model_mobilenet.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase1_mobilenet = [
    ModelCheckpoint(
        'best_phase1_mobilenet.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-7,
        verbose=1
    )
]

history_phase1_mobilenet = model_mobilenet.fit(
    train_generator_mobilenet,
    epochs=10,
    validation_data=valid_generator_mobilenet,
    callbacks=callbacks_phase1_mobilenet,
    verbose=1
)

print(f"\nPhase 1 best val accuracy: {max(history_phase1_mobilenet.history['val_accuracy']):.4f}")

print("="*60)
print("  PHASE 2 — Fine-Tuning Last 30 Layers")
print("="*60)

base_model_mobilenet.trainable = True
for layer in base_model_mobilenet.layers[:-30]:
    layer.trainable = False

print(f"Trainable layers now: {len([l for l in model_mobilenet.layers if l.trainable])}")

model_mobilenet.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase2_mobilenet = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        'best_mobilenetv2.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-8,
        verbose=1
    )
]

history_phase2_mobilenet = model_mobilenet.fit(
    train_generator_mobilenet,
    epochs=20,
    validation_data=valid_generator_mobilenet,
    callbacks=callbacks_phase2_mobilenet,
    verbose=1
)

print(f"\nPhase 2 best val accuracy: {max(history_phase2_mobilenet.history['val_accuracy']):.4f}")

print("="*60)
print("  EVALUATING MOBILENETV2 ON TEST SET")
print("="*60)

model_mobilenet.load_weights('best_mobilenetv2.keras')

test_loss_mobilenet, test_accuracy_mobilenet = model_mobilenet.evaluate(test_generator_mobilenet, verbose=1)
print(f"\nTest Loss     : {test_loss_mobilenet:.4f}")
print(f"Test Accuracy : {test_accuracy_mobilenet:.4f} ({test_accuracy_mobilenet*100:.2f}%)")

test_generator_mobilenet.reset()
y_pred_probs_mobilenet = model_mobilenet.predict(test_generator_mobilenet, verbose=1)
y_pred_mobilenet = np.argmax(y_pred_probs_mobilenet, axis=1)
y_true_mobilenet = test_generator_mobilenet.classes

print("\n" + "="*60)
print("  CLASSIFICATION REPORT")
print("="*60)
print(classification_report(y_true_mobilenet, y_pred_mobilenet, target_names=class_names_mobilenet))

def plot_training_history_mobilenet(h1, h2):
    acc      = h1.history['accuracy']     + h2.history['accuracy']
    val_acc  = h1.history['val_accuracy'] + h2.history['val_accuracy']
    loss     = h1.history['loss']         + h2.history['loss']
    val_loss = h1.history['val_loss']     + h2.history['val_loss']
    epochs   = range(1, len(acc) + 1)
    phase1_end = len(h1.history['accuracy'])

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle('MobileNetV2 — Training History', fontsize=16, fontweight='bold')

    axes[0].plot(epochs, acc,     'b-o', markersize=3, label='Train Accuracy')
    axes[0].plot(epochs, val_acc, 'r-o', markersize=3, label='Val Accuracy')
    axes[0].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[0].fill_betweenx([0, 1], 1, phase1_end, alpha=0.05, color='blue')
    axes[0].fill_betweenx([0, 1], phase1_end, len(epochs), alpha=0.05, color='green')
    axes[0].set_title('Accuracy', fontsize=13)
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[0].set_ylim([0, 1])

    axes[1].plot(epochs, loss,     'b-o', markersize=3, label='Train Loss')
    axes[1].plot(epochs, val_loss, 'r-o', markersize=3, label='Val Loss')
    axes[1].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[1].set_title('Loss', fontsize=13)
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('training_curves_mobilenetv2.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Training curves saved.")

plot_training_history_mobilenet(history_phase1_mobilenet, history_phase2_mobilenet)

def plot_confusion_matrix_mobilenet(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))
    fig.suptitle('MobileNetV2 — Confusion Matrix', fontsize=16, fontweight='bold')

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[0])
    axes[0].set_title('Counts', fontsize=13)
    axes[0].set_xlabel('Predicted Label', fontsize=11)
    axes[0].set_ylabel('True Label', fontsize=11)

    sns.heatmap(cm_percent, annot=True, fmt='.1f', cmap='Greens',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[1])
    axes[1].set_title('Percentage (%)', fontsize=13)
    axes[1].set_xlabel('Predicted Label', fontsize=11)
    axes[1].set_ylabel('True Label', fontsize=11)

    plt.tight_layout()
    plt.savefig('confusion_matrix_mobilenetv2.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Confusion matrix saved.")

plot_confusion_matrix_mobilenet(y_true_mobilenet, y_pred_mobilenet, class_names_mobilenet)

def plot_per_class_accuracy_mobilenet(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100

    colors = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0']
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.bar(class_names, per_class_acc, color=colors, edgecolor='white',
                  linewidth=1.5, width=0.5)

    for bar, acc in zip(bars, per_class_acc):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{acc:.2f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')

    ax.set_title('MobileNetV2 — Per-Class Accuracy on Test Set',
                 fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Tumor Class', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_ylim([0, 110])
    ax.axhline(y=np.mean(per_class_acc), color='red', linestyle='--',
               alpha=0.7, label=f'Mean: {np.mean(per_class_acc):.2f}%')
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig('per_class_accuracy_mobilenetv2.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Per-class accuracy chart saved.")

plot_per_class_accuracy_mobilenet(y_true_mobilenet, y_pred_mobilenet, class_names_mobilenet)

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.preprocessing import image
from google.colab import files

def predict_single_image_mobilenet(model, class_names):
    print("Please upload an MRI image...")
    uploaded = files.upload()

    for img_name in uploaded.keys():
        img = image.load_img(img_name, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = mobilenet_preprocess(img_array)
        img_batch = np.expand_dims(img_array, axis=0)

        predictions = model_mobilenet.predict(img_batch, verbose=0)[0]
        pred_class  = class_names[np.argmax(predictions)]
        confidence  = np.max(predictions) * 100

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle('Brain Tumor Classification — MobileNetV2',
                     fontsize=14, fontweight='bold')

        img_display = image.load_img(img_name, target_size=(224, 224))
        axes[0].imshow(img_display)
        axes[0].set_title(f'Uploaded Image: {img_name}', fontsize=11)
        axes[0].axis('off')

        colors = ['#4CAF50' if c == pred_class else '#B0BEC5' for c in class_names]
        bars = axes[1].barh(class_names, predictions * 100,
                            color=colors, edgecolor='white', height=0.5)

        for bar, prob in zip(bars, predictions * 100):
            axes[1].text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                         f'{prob:.2f}%', va='center', fontsize=11, fontweight='bold')

        axes[1].set_xlim([0, 115])
        axes[1].set_xlabel('Confidence (%)', fontsize=11)
        axes[1].set_title('Prediction Confidence per Class', fontsize=11)
        axes[1].spines['top'].set_visible(False)
        axes[1].spines['right'].set_visible(False)
        axes[1].grid(axis='x', alpha=0.3)

        fig.text(0.5, 0.01,
                 f'Prediction: {pred_class}   |   Confidence: {confidence:.2f}%',
                 ha='center', fontsize=13, fontweight='bold',
                 color='white',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor='#4CAF50', alpha=0.9))

        plt.tight_layout(rect=[0, 0.06, 1, 1])
        plt.savefig(f'prediction_mobilenet_{img_name}', dpi=150, bbox_inches='tight')
        plt.show()

        print("\n" + "="*50)
        print(f"  Image      : {img_name}")
        print(f"  Prediction : {pred_class}")
        print(f"  Confidence : {confidence:.2f}%")
        print("─"*50)
        for cls, prob in zip(class_names, predictions):
            marker = " ◄ PREDICTED" if cls == pred_class else ""
            print(f"  {cls:<15}: {prob*100:.2f}%{marker}")
        print("="*50)

predict_single_image_mobilenet(model_mobilenet, class_names_mobilenet)

import os
from google.colab import files

model_mobilenet.save('mobilenetv2_brain_tumor.keras')
print("Model saved as: mobilenetv2_brain_tumor.keras")

model_mobilenet.save('/content/drive/MyDrive/mobilenetv2_brain_tumor.keras')
print("Model also saved to Google Drive.")

files_to_download = [
    'mobilenetv2_brain_tumor.keras',
    'training_curves_mobilenetv2.png',
    'confusion_matrix_mobilenetv2.png',
    'per_class_accuracy_mobilenetv2.png',
]

for f in files_to_download:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
    else:
        print(f"SKIPPED (not found): {f}")

print("\nMobileNetV2 done! Ready for ResNet-50.")

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess

train_generator_resnet = ImageDataGenerator(preprocessing_function=resnet_preprocess).flow_from_directory(
    TRAIN_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

valid_generator_resnet = ImageDataGenerator(preprocessing_function=resnet_preprocess).flow_from_directory(
    VALID_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

test_generator_resnet = ImageDataGenerator(preprocessing_function=resnet_preprocess).flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

class_names_resnet = [k for k, v in sorted(train_generator_resnet.class_indices.items(), key=lambda x: x[1])]

print("Class names:", class_names_resnet)
print(f"Train samples : {train_generator_resnet.samples}")
print(f"Valid samples : {valid_generator_resnet.samples}")
print(f"Test  samples : {test_generator_resnet.samples}")

def build_resnet50(num_classes=4):
    base_model = ResNet50(
        weights='imagenet',
        include_top=False,
        input_shape=(224, 224, 3)
    )
    base_model.trainable = False

    x = base_model.output
    x = GlobalAveragePooling2D(name='gap_resnet')(x)
    x = BatchNormalization(name='bn_resnet')(x)
    x = Dense(256, activation='relu', name='dense_256_resnet')(x)
    x = Dropout(0.4, name='dropout_resnet')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions_resnet')(x)

    model_resnet = Model(inputs=base_model.input, outputs=outputs)
    return model_resnet, base_model

model_resnet, base_model_resnet = build_resnet50(NUM_CLASSES)

print(f"Total layers      : {len(model_resnet.layers)}")
print(f"Trainable layers  : {len([l for l in model_resnet.layers if l.trainable])}")
print(f"Frozen layers     : {len([l for l in model_resnet.layers if not l.trainable])}")
model_resnet.summary()

print("="*60)
print("  PHASE 1 — Training Classification Head (Base Frozen)")
print("="*60)

model_resnet.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase1_resnet = [
    ModelCheckpoint(
        'best_phase1_resnet.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-7,
        verbose=1
    )
]

history_phase1_resnet = model_resnet.fit(
    train_generator_resnet,
    epochs=10,
    validation_data=valid_generator_resnet,
    callbacks=callbacks_phase1_resnet,
    verbose=1
)

print(f"\nPhase 1 best val accuracy: {max(history_phase1_resnet.history['val_accuracy']):.4f}")

print("="*60)
print("  PHASE 2 — Fine-Tuning Last 30 Layers")
print("="*60)

base_model_resnet.trainable = True
for layer in base_model_resnet.layers[:-30]:
    layer.trainable = False

print(f"Trainable layers now: {len([l for l in model_resnet.layers if l.trainable])}")

model_resnet.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

callbacks_phase2_resnet = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),
    ModelCheckpoint(
        'best_resnet50.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=3,
        min_lr=1e-8,
        verbose=1
    )
]

history_phase2_resnet = model_resnet.fit(
    train_generator_resnet,
    epochs=20,
    validation_data=valid_generator_resnet,
    callbacks=callbacks_phase2_resnet,
    verbose=1
)

print(f"\nPhase 2 best val accuracy: {max(history_phase2_resnet.history['val_accuracy']):.4f}")

print("="*60)
print("  EVALUATING RESNET-50 ON TEST SET")
print("="*60)

model_resnet.load_weights('best_resnet50.keras')

test_loss_resnet, test_accuracy_resnet = model_resnet.evaluate(test_generator_resnet, verbose=1)
print(f"\nTest Loss     : {test_loss_resnet:.4f}")
print(f"Test Accuracy : {test_accuracy_resnet:.4f} ({test_accuracy_resnet*100:.2f}%)")

test_generator_resnet.reset()
y_pred_probs_resnet = model_resnet.predict(test_generator_resnet, verbose=1)
y_pred_resnet = np.argmax(y_pred_probs_resnet, axis=1)
y_true_resnet = test_generator_resnet.classes

print("\n" + "="*60)
print("  CLASSIFICATION REPORT")
print("="*60)
print(classification_report(y_true_resnet, y_pred_resnet, target_names=class_names_resnet))

def plot_training_history_resnet(h1, h2):
    acc      = h1.history['accuracy']     + h2.history['accuracy']
    val_acc  = h1.history['val_accuracy'] + h2.history['val_accuracy']
    loss     = h1.history['loss']         + h2.history['loss']
    val_loss = h1.history['val_loss']     + h2.history['val_loss']
    epochs   = range(1, len(acc) + 1)
    phase1_end = len(h1.history['accuracy'])

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.suptitle('ResNet-50 — Training History', fontsize=16, fontweight='bold')

    axes[0].plot(epochs, acc,     'b-o', markersize=3, label='Train Accuracy')
    axes[0].plot(epochs, val_acc, 'r-o', markersize=3, label='Val Accuracy')
    axes[0].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[0].fill_betweenx([0, 1], 1, phase1_end, alpha=0.05, color='blue')
    axes[0].fill_betweenx([0, 1], phase1_end, len(epochs), alpha=0.05, color='green')
    axes[0].set_title('Accuracy', fontsize=13)
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    axes[0].set_ylim([0, 1])

    axes[1].plot(epochs, loss,     'b-o', markersize=3, label='Train Loss')
    axes[1].plot(epochs, val_loss, 'r-o', markersize=3, label='Val Loss')
    axes[1].axvline(x=phase1_end, color='gray', linestyle='--', alpha=0.7, label='Fine-tuning starts')
    axes[1].set_title('Loss', fontsize=13)
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('training_curves_resnet50.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Training curves saved.")

plot_training_history_resnet(history_phase1_resnet, history_phase2_resnet)

def plot_confusion_matrix_resnet(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))
    fig.suptitle('ResNet-50 — Confusion Matrix', fontsize=16, fontweight='bold')

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[0])
    axes[0].set_title('Counts', fontsize=13)
    axes[0].set_xlabel('Predicted Label', fontsize=11)
    axes[0].set_ylabel('True Label', fontsize=11)

    sns.heatmap(cm_percent, annot=True, fmt='.1f', cmap='Greens',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[1])
    axes[1].set_title('Percentage (%)', fontsize=13)
    axes[1].set_xlabel('Predicted Label', fontsize=11)
    axes[1].set_ylabel('True Label', fontsize=11)

    plt.tight_layout()
    plt.savefig('confusion_matrix_resnet50.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Confusion matrix saved.")

plot_confusion_matrix_resnet(y_true_resnet, y_pred_resnet, class_names_resnet)

def plot_per_class_accuracy_resnet(y_true, y_pred, class_names):
    cm = confusion_matrix(y_true, y_pred)
    per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100

    colors = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0']
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.bar(class_names, per_class_acc, color=colors, edgecolor='white',
                  linewidth=1.5, width=0.5)

    for bar, acc in zip(bars, per_class_acc):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{acc:.2f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')

    ax.set_title('ResNet-50 — Per-Class Accuracy on Test Set',
                 fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Tumor Class', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_ylim([0, 110])
    ax.axhline(y=np.mean(per_class_acc), color='red', linestyle='--',
               alpha=0.7, label=f'Mean: {np.mean(per_class_acc):.2f}%')
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig('per_class_accuracy_resnet50.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Per-class accuracy chart saved.")

plot_per_class_accuracy_resnet(y_true_resnet, y_pred_resnet, class_names_resnet)

from tensorflow.keras.preprocessing import image

def predict_single_image_resnet(model, class_names):
    print("Please upload an MRI image...")
    uploaded = files.upload()

    for img_name in uploaded.keys():
        img = image.load_img(img_name, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = resnet_preprocess(img_array)
        img_batch = np.expand_dims(img_array, axis=0)

        predictions = model_resnet.predict(img_batch, verbose=0)[0]
        pred_class  = class_names[np.argmax(predictions)]
        confidence  = np.max(predictions) * 100

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle('Brain Tumor Classification — ResNet-50',
                     fontsize=14, fontweight='bold')

        img_display = image.load_img(img_name, target_size=(224, 224))
        axes[0].imshow(img_display)
        axes[0].set_title(f'Uploaded Image: {img_name}', fontsize=11)
        axes[0].axis('off')

        colors = ['#4CAF50' if c == pred_class else '#B0BEC5' for c in class_names]
        bars = axes[1].barh(class_names, predictions * 100,
                            color=colors, edgecolor='white', height=0.5)

        for bar, prob in zip(bars, predictions * 100):
            axes[1].text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                         f'{prob:.2f}%', va='center', fontsize=11, fontweight='bold')

        axes[1].set_xlim([0, 115])
        axes[1].set_xlabel('Confidence (%)', fontsize=11)
        axes[1].set_title('Prediction Confidence per Class', fontsize=11)
        axes[1].spines['top'].set_visible(False)
        axes[1].spines['right'].set_visible(False)
        axes[1].grid(axis='x', alpha=0.3)

        fig.text(0.5, 0.01,
                 f'Prediction: {pred_class}   |   Confidence: {confidence:.2f}%',
                 ha='center', fontsize=13, fontweight='bold',
                 color='white',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor='#4CAF50', alpha=0.9))

        plt.tight_layout(rect=[0, 0.06, 1, 1])
        plt.savefig(f'prediction_resnet_{img_name}', dpi=150, bbox_inches='tight')
        plt.show()

        print("\n" + "="*50)
        print(f"  Image      : {img_name}")
        print(f"  Prediction : {pred_class}")
        print(f"  Confidence : {confidence:.2f}%")
        print("─"*50)
        for cls, prob in zip(class_names, predictions):
            marker = " ◄ PREDICTED" if cls == pred_class else ""
            print(f"  {cls:<15}: {prob*100:.2f}%{marker}")
        print("="*50)

predict_single_image_resnet(model_resnet, class_names_resnet)

import os
from google.colab import files

model_resnet.save('resnet50_brain_tumor.keras')
print("Model saved as: resnet50_brain_tumor.keras")

model_resnet.save('/content/drive/MyDrive/resnet50_brain_tumor.keras')
print("Model also saved to Google Drive.")

files_to_download = [
    'resnet50_brain_tumor.keras',
    'training_curves_resnet50.png',
    'confusion_matrix_resnet50.png',
    'per_class_accuracy_resnet50.png',
]

for f in files_to_download:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
    else:
        print(f"SKIPPED (not found): {f}")

print("\nAll 3 models complete! Ready for Flask app.")

from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocess
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from collections import Counter
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches

def compare_all_models(model_eff, model_mob, model_res, class_names):
    print("Please upload an MRI image...")
    uploaded = files.upload()

    for img_name in uploaded.keys():
        img       = image.load_img(img_name, target_size=(224, 224))
        img_array = image.img_to_array(img)

        img_eff = np.expand_dims(efficientnet_preprocess(img_array.copy()), axis=0)
        img_mob = np.expand_dims(mobilenet_preprocess(img_array.copy()),    axis=0)
        img_res = np.expand_dims(resnet_preprocess(img_array.copy()),       axis=0)

        pred_eff = model_eff.predict(img_eff, verbose=0)[0]
        pred_mob = model_mob.predict(img_mob, verbose=0)[0]
        pred_res = model_res.predict(img_res, verbose=0)[0]

        models      = ['EfficientNetB0', 'MobileNetV2', 'ResNet-50']
        predictions = [pred_eff, pred_mob, pred_res]
        model_colors= ['#1565C0', '#BF360C', '#1B5E20']
        confidences = [np.max(p) * 100 for p in predictions]
        pred_classes= [class_names[np.argmax(p)] for p in predictions]

        # Majority voting
        vote_counts     = Counter(pred_classes)
        final_diagnosis = vote_counts.most_common(1)[0][0]
        agreeing_indices= [i for i, c in enumerate(pred_classes) if c == final_diagnosis]
        best_idx        = max(agreeing_indices, key=lambda i: confidences[i])
        best_model      = models[best_idx]
        best_conf       = confidences[best_idx]

        # ── Figure layout ──────────────────────────────────────────
        fig = plt.figure(figsize=(22, 13), facecolor='#0D1117')
        fig.patch.set_facecolor('#0D1117')
        gs  = gridspec.GridSpec(2, 4, figure=fig,
                                hspace=0.45, wspace=0.35,
                                left=0.04, right=0.97,
                                top=0.88,  bottom=0.13)

        # ── Title ──────────────────────────────────────────────────
        fig.text(0.5, 0.95,
                 'Brain Tumor Classification — Model Comparison',
                 ha='center', va='center', fontsize=17,
                 fontweight='bold', color='white')
        fig.text(0.5, 0.91,
                 f'Final Diagnosis: {final_diagnosis}   •   Best Model: {best_model}   •   Confidence: {best_conf:.2f}%   •   Votes: {vote_counts[final_diagnosis]}/3',
                 ha='center', va='center', fontsize=12, color='#90CAF9')

        # ── MRI image (spans both rows, left column) ───────────────
        ax_img = fig.add_subplot(gs[:, 0])
        ax_img.imshow(image.load_img(img_name, target_size=(224, 224)))
        ax_img.set_title('MRI Scan', color='white', fontsize=13,
                         fontweight='bold', pad=10)
        ax_img.axis('off')
        for spine in ax_img.spines.values():
            spine.set_edgecolor('#334155')
            spine.set_linewidth(1.5)

        # ── Class labels for color key ─────────────────────────────
        class_palette = ['#42A5F5', '#EF5350', '#66BB6A', '#FFA726']

        # ── Per-model bar charts ───────────────────────────────────
        row_map = [(0,1),(0,2),(0,3)]
        for i, (model_name, pred, mcolor) in enumerate(zip(models, predictions, model_colors)):
            r, c   = row_map[i]
            ax     = fig.add_subplot(gs[r, c])
            ax.set_facecolor('#161B22')

            pred_class = pred_classes[i]
            confidence = confidences[i]
            bar_colors = [class_palette[j] if class_names[j] == pred_class
                          else '#2D3748' for j in range(len(class_names))]

            bars = ax.barh(class_names, pred * 100,
                           color=bar_colors, edgecolor='#0D1117',
                           linewidth=0.8, height=0.55)

            for bar, prob in zip(bars, pred * 100):
                if prob > 5:
                    ax.text(bar.get_width() - 1.5,
                            bar.get_y() + bar.get_height() / 2,
                            f'{prob:.1f}%', va='center', ha='right',
                            fontsize=9, fontweight='bold', color='white')
                else:
                    ax.text(bar.get_width() + 1,
                            bar.get_y() + bar.get_height() / 2,
                            f'{prob:.1f}%', va='center', ha='left',
                            fontsize=9, color='#90A4AE')

            star = '  ⭐ BEST' if i == best_idx else ''
            ax.set_title(f'{model_name}{star}',
                         color='#FFD700' if i == best_idx else 'white',
                         fontsize=10, fontweight='bold', pad=8)
            ax.text(0.5, -0.16, f'{pred_class}  {confidence:.1f}%',
                    transform=ax.transAxes, ha='center',
                    fontsize=10, fontweight='bold',
                    color='#69F0AE' if i == best_idx else '#90CAF9')

            ax.set_xlim([0, 108])
            ax.set_facecolor('#161B22')
            ax.tick_params(colors='#90A4AE', labelsize=9)
            ax.xaxis.label.set_color('#90A4AE')
            for spine in ax.spines.values():
                spine.set_edgecolor('#334155')
                spine.set_linewidth(0.8)
            ax.grid(axis='x', color='#334155', linewidth=0.5, alpha=0.6)

        # ── Vote summary bar (bottom row) ──────────────────────────
        ax_vote = fig.add_subplot(gs[1, 1:])
        ax_vote.set_facecolor('#161B22')

        vote_vals  = [vote_counts.get(c, 0) for c in class_names]
        vote_colors= [class_palette[j] if vote_vals[j] > 0 else '#2D3748'
                      for j in range(len(class_names))]

        bars2 = ax_vote.bar(class_names, vote_vals,
                            color=vote_colors, edgecolor='#0D1117',
                            linewidth=0.8, width=0.5)

        for bar, v in zip(bars2, vote_vals):
            if v > 0:
                ax_vote.text(bar.get_x() + bar.get_width()/2,
                             bar.get_height() + 0.05,
                             f'{v}/3 votes', ha='center', va='bottom',
                             fontsize=10, fontweight='bold', color='#69F0AE')

        ax_vote.set_title('Voting Summary — All Models',
                          color='white', fontsize=11,
                          fontweight='bold', pad=8)
        ax_vote.set_ylim([0, 3.8])
        ax_vote.set_yticks([0, 1, 2, 3])
        ax_vote.tick_params(colors='#90A4AE', labelsize=9)
        for spine in ax_vote.spines.values():
            spine.set_edgecolor('#334155')
            spine.set_linewidth(0.8)
        ax_vote.grid(axis='y', color='#334155', linewidth=0.5, alpha=0.6)

        # ── Final verdict box ──────────────────────────────────────
        verdict_color = '#1B5E20' if final_diagnosis != 'no_tumor' else '#0D47A1'
        fig.text(0.5, 0.04,
                 f'✅  FINAL DIAGNOSIS:  {final_diagnosis.upper()}     |     BEST MODEL:  {best_model}     |     CONFIDENCE:  {best_conf:.2f}%     |     AGREEMENT:  {vote_counts[final_diagnosis]}/3',
                 ha='center', va='center', fontsize=12,
                 fontweight='bold', color='white',
                 bbox=dict(boxstyle='round,pad=0.7',
                           facecolor=verdict_color,
                           edgecolor='#69F0AE',
                           linewidth=1.5,
                           alpha=0.95))

        plt.savefig(f'comparison_{img_name}', dpi=150,
                    bbox_inches='tight', facecolor='#0D1117')
        plt.show()

        # ── Console summary ────────────────────────────────────────
        print("\n" + "="*60)
        print("  MODEL COMPARISON SUMMARY")
        print("="*60)
        print(f"  {'Model':<20} {'Prediction':<15} {'Confidence'}")
        print("─"*60)
        for i, (m, p, c) in enumerate(zip(models, pred_classes, confidences)):
            star = "  ⭐ BEST" if i == best_idx else ""
            print(f"  {m:<20} {p:<15} {c:.2f}%{star}")
        print("="*60)
        print(f"\n  Final Diagnosis : {final_diagnosis}")
        print(f"  Votes           : {vote_counts[final_diagnosis]}/3 models agree")
        print(f"  Best Model      : {best_model}")
        print(f"  Confidence      : {best_conf:.2f}%")
        print("="*60)

compare_all_models(model, model_mobilenet, model_resnet, class_names_resnet)

from google.colab import drive
drive.mount('/content/drive')

!pip install kaggle --quiet
print("Done!")

import os
import numpy as np
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

!cp "/content/drive/MyDrive/dataset (2).zip" /content/
!unzip -q /content/"dataset (2).zip" -d /content/my_dataset
print("Done!")
print(os.listdir('/content/my_dataset'))

import shutil

# Create folders
os.makedirs('/content/brain_detector/train/brain', exist_ok=True)
os.makedirs('/content/brain_detector/train/not_brain', exist_ok=True)
os.makedirs('/content/brain_detector/test/brain', exist_ok=True)
os.makedirs('/content/brain_detector/test/not_brain', exist_ok=True)

# Copy brain MRI images from your existing dataset
brain_sources = [
    '/content/my_dataset/dataset/train/glioma',
    '/content/my_dataset/dataset/train/meningioma',
    '/content/my_dataset/dataset/train/no_tumor',
    '/content/my_dataset/dataset/train/pituitary'
]

count = 0
for src in brain_sources:
    if os.path.exists(src):
        images = os.listdir(src)[:300]
        for img in images[:250]:
            shutil.copy(os.path.join(src, img), '/content/brain_detector/train/brain/')
        for img in images[250:300]:
            shutil.copy(os.path.join(src, img), '/content/brain_detector/test/brain/')
        count += len(images)

print(f"Brain images copied: {count}")

# Download not_brain images using CIFAR10
from PIL import Image
(x_train, _), (x_test, _) = tf.keras.datasets.cifar10.load_data()

for i in range(1000):
    img = Image.fromarray(x_train[i])
    img = img.convert('L')
    img.save(f'/content/brain_detector/train/not_brain/cifar_{i}.png')

for i in range(200):
    img = Image.fromarray(x_test[i])
    img = img.convert('L')
    img.save(f'/content/brain_detector/test/not_brain/cifar_{i}.png')

print(f"Brain train     : {len(os.listdir('/content/brain_detector/train/brain'))}")
print(f"Not brain train : {len(os.listdir('/content/brain_detector/train/not_brain'))}")
print(f"Brain test      : {len(os.listdir('/content/brain_detector/test/brain'))}")
print(f"Not brain test  : {len(os.listdir('/content/brain_detector/test/not_brain'))}")
print("Dataset ready!")

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Data generators
train_gen = ImageDataGenerator(preprocessing_function=preprocess_input).flow_from_directory(
    '/content/brain_detector/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=True,
    seed=42
)

test_gen = ImageDataGenerator(preprocessing_function=preprocess_input).flow_from_directory(
    '/content/brain_detector/test',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

print("Classes:", train_gen.class_indices)
print(f"Train samples: {train_gen.samples}")
print(f"Test  samples: {test_gen.samples}")

# Build detector model
base = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base.trainable = False

x = base.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.3)(x)
output = Dense(1, activation='sigmoid')(x)

detector = Model(inputs=base.input, outputs=output)

detector.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
    ModelCheckpoint('best_brain_detector.keras', monitor='val_accuracy', save_best_only=True, verbose=1)
]

print("\nTraining Brain MRI Detector...")
history = detector.fit(
    train_gen,
    epochs=15,
    validation_data=test_gen,
    callbacks=callbacks,
    verbose=1
)

print(f"\nBest val accuracy: {max(history.history['val_accuracy']):.4f}")

# Evaluate on test set
test_loss, test_accuracy = detector.evaluate(test_gen, verbose=1)
print(f"\nDetector Test Accuracy : {test_accuracy*100:.2f}%")
print(f"Detector Test Loss     : {test_loss:.4f}")

# Save to Google Drive
detector.save('brain_detector.keras')
detector.save('/content/drive/MyDrive/brain_detector.keras')
print("\nDetector saved to Google Drive!")

# Download to laptop
from google.colab import files
files.download('brain_detector.keras')
print("Downloaded successfully!")

import json
import zipfile
import shutil

def fix_model(input_path, output_path):
    shutil.copy(input_path, output_path)

    with zipfile.ZipFile(output_path, 'r') as z:
        config = json.loads(z.read('config.json'))

    config_str = json.dumps(config)
    config_str = config_str.replace('"quantization_config": null,', '')
    config_str = config_str.replace(', "quantization_config": null', '')

    with zipfile.ZipFile(output_path, 'a') as z:
        z.writestr('config.json', config_str)

    print(f"Fixed: {output_path}")

fix_model('brain_detector.keras', 'brain_detector_fixed.keras')

# Save to Drive
shutil.copy('brain_detector_fixed.keras', '/content/drive/MyDrive/brain_detector_fixed.keras')
print("Saved to Google Drive!")

# Download
from google.colab import files
files.download('brain_detector_fixed.keras')
print("Downloaded!")

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.applications import EfficientNetB0, MobileNetV2, ResNet50
from tensorflow.keras.applications.efficientnet import preprocess_input as eff_preprocess
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mob_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as res_preprocess
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

A

!cp "/content/drive/MyDrive/dataset (2).zip" /content/
!unzip -q /content/"dataset (2).zip" -d /content/my_dataset
print("Done!")
print(os.listdir('/content/my_dataset'))

from PIL import Image

os.makedirs('/content/my_dataset/dataset/train/unknown', exist_ok=True)
os.makedirs('/content/my_dataset/dataset/valid/unknown', exist_ok=True)
os.makedirs('/content/my_dataset/dataset/test/unknown', exist_ok=True)

(x_train, _), (x_test, _) = tf.keras.datasets.cifar10.load_data()
(x_train2, _), (x_test2, _) = tf.keras.datasets.cifar100.load_data()

for i in range(2000):
    Image.fromarray(x_train[i]).resize((224,224)).save(f'/content/my_dataset/dataset/train/unknown/c10_{i}.png')
    Image.fromarray(x_train2[i]).resize((224,224)).save(f'/content/my_dataset/dataset/train/unknown/c100_{i}.png')

for i in range(500):
    Image.fromarray(x_test[i]).resize((224,224)).save(f'/content/my_dataset/dataset/valid/unknown/c10_{i}.png')
    Image.fromarray(x_test2[i]).resize((224,224)).save(f'/content/my_dataset/dataset/test/unknown/c10_{i}.png')

print("Train unknown:", len(os.listdir('/content/my_dataset/dataset/train/unknown')))
print("Valid unknown:", len(os.listdir('/content/my_dataset/dataset/valid/unknown')))
print("Test  unknown:", len(os.listdir('/content/my_dataset/dataset/test/unknown')))
print("Done!")

TRAIN_DIR = '/content/my_dataset/dataset/train'
VALID_DIR = '/content/my_dataset/dataset/valid'
TEST_DIR  = '/content/my_dataset/dataset/test'

IMG_SIZE    = (224, 224)
BATCH_SIZE  = 32
NUM_CLASSES = 5

tf.random.set_seed(42)
np.random.seed(42)

print("Classes in train:", sorted(os.listdir(TRAIN_DIR)))
print("NUM_CLASSES:", NUM_CLASSES)

train_gen_eff = ImageDataGenerator(preprocessing_function=eff_preprocess).flow_from_directory(
    TRAIN_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=True, seed=42)

valid_gen_eff = ImageDataGenerator(preprocessing_function=eff_preprocess).flow_from_directory(
    VALID_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

test_gen_eff = ImageDataGenerator(preprocessing_function=eff_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

class_names_eff = [k for k, v in sorted(train_gen_eff.class_indices.items(), key=lambda x: x[1])]
print("Classes:", class_names_eff)
print(f"Train: {train_gen_eff.samples} | Valid: {valid_gen_eff.samples} | Test: {test_gen_eff.samples}")

def build_efficientnetb0(num_classes=5):
    base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224,224,3))
    base_model.trainable = False
    x = base_model.output
    x = GlobalAveragePooling2D(name='gap')(x)
    x = BatchNormalization(name='bn')(x)
    x = Dense(256, activation='relu', name='dense_256')(x)
    x = Dropout(0.4, name='dropout')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions')(x)
    model = Model(inputs=base_model.input, outputs=outputs)
    return model, base_model

model_eff, base_eff = build_efficientnetb0(NUM_CLASSES)
print(f"Total layers: {len(model_eff.layers)}")
print(f"Trainable   : {len([l for l in model_eff.layers if l.trainable])}")

model_eff.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

h1_eff = model_eff.fit(
    train_gen_eff, epochs=10, validation_data=valid_gen_eff,
    callbacks=[
        ModelCheckpoint('best_phase1_eff.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 1 best val accuracy: {max(h1_eff.history['val_accuracy']):.4f}")

base_eff.trainable = True
for layer in base_eff.layers[:-30]:
    layer.trainable = False

model_eff.compile(optimizer=Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

h2_eff = model_eff.fit(
    train_gen_eff, epochs=20, validation_data=valid_gen_eff,
    callbacks=[
        EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
        ModelCheckpoint('best_eff.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 2 best val accuracy: {max(h2_eff.history['val_accuracy']):.4f}")

model_eff.load_weights('best_eff.keras')
loss, acc = model_eff.evaluate(test_gen_eff, verbose=1)
print(f"EfficientNetB0 Test Accuracy: {acc*100:.2f}%")

test_gen_eff.reset()
y_pred = np.argmax(model_eff.predict(test_gen_eff, verbose=1), axis=1)
y_true = test_gen_eff.classes
print(classification_report(y_true, y_pred, target_names=class_names_eff))

model_eff.save('efficientnetb0_v2.keras')
model_eff.save('/content/drive/MyDrive/efficientnetb0_v2.keras')
print("EfficientNetB0 saved!")

train_gen_mob = ImageDataGenerator(preprocessing_function=mob_preprocess).flow_from_directory(
    TRAIN_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=True, seed=42)

valid_gen_mob = ImageDataGenerator(preprocessing_function=mob_preprocess).flow_from_directory(
    VALID_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

test_gen_mob = ImageDataGenerator(preprocessing_function=mob_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

class_names_mob = [k for k, v in sorted(train_gen_mob.class_indices.items(), key=lambda x: x[1])]
print("Classes:", class_names_mob)
print(f"Train: {train_gen_mob.samples} | Valid: {valid_gen_mob.samples} | Test: {test_gen_mob.samples}")

def build_mobilenetv2(num_classes=5):
    base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))
    base_model.trainable = False
    x = base_model.output
    x = GlobalAveragePooling2D(name='gap_mob')(x)
    x = BatchNormalization(name='bn_mob')(x)
    x = Dense(256, activation='relu', name='dense_256_mob')(x)
    x = Dropout(0.4, name='dropout_mob')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions_mob')(x)
    model = Model(inputs=base_model.input, outputs=outputs)
    return model, base_model

model_mob, base_mob = build_mobilenetv2(NUM_CLASSES)
print(f"Total layers: {len(model_mob.layers)}")
print(f"Trainable   : {len([l for l in model_mob.layers if l.trainable])}")

model_mob.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

h1_mob = model_mob.fit(
    train_gen_mob, epochs=10, validation_data=valid_gen_mob,
    callbacks=[
        ModelCheckpoint('best_phase1_mob.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 1 best val accuracy: {max(h1_mob.history['val_accuracy']):.4f}")

base_mob.trainable = True
for layer in base_mob.layers[:-30]:
    layer.trainable = False

model_mob.compile(optimizer=Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

h2_mob = model_mob.fit(
    train_gen_mob, epochs=20, validation_data=valid_gen_mob,
    callbacks=[
        EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
        ModelCheckpoint('best_mob.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 2 best val accuracy: {max(h2_mob.history['val_accuracy']):.4f}")

model_mob.load_weights('best_mob.keras')
loss, acc = model_mob.evaluate(test_gen_mob, verbose=1)
print(f"MobileNetV2 Test Accuracy: {acc*100:.2f}%")

test_gen_mob.reset()
y_pred_mob = np.argmax(model_mob.predict(test_gen_mob, verbose=1), axis=1)
y_true_mob = test_gen_mob.classes
print(classification_report(y_true_mob, y_pred_mob, target_names=class_names_mob))

model_mob.save('mobilenetv2_v2.keras')
model_mob.save('/content/drive/MyDrive/mobilenetv2_v2.keras')
print("MobileNetV2 saved!")

train_gen_res = ImageDataGenerator(preprocessing_function=res_preprocess).flow_from_directory(
    TRAIN_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=True, seed=42)

valid_gen_res = ImageDataGenerator(preprocessing_function=res_preprocess).flow_from_directory(
    VALID_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

test_gen_res = ImageDataGenerator(preprocessing_function=res_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False)

class_names_res = [k for k, v in sorted(train_gen_res.class_indices.items(), key=lambda x: x[1])]
print("Classes:", class_names_res)
print(f"Train: {train_gen_res.samples} | Valid: {valid_gen_res.samples} | Test: {test_gen_res.samples}")

def build_resnet50(num_classes=5):
    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
    base_model.trainable = False
    x = base_model.output
    x = GlobalAveragePooling2D(name='gap_res')(x)
    x = BatchNormalization(name='bn_res')(x)
    x = Dense(256, activation='relu', name='dense_256_res')(x)
    x = Dropout(0.4, name='dropout_res')(x)
    outputs = Dense(num_classes, activation='softmax', name='predictions_res')(x)
    model = Model(inputs=base_model.input, outputs=outputs)
    return model, base_model

model_res, base_res = build_resnet50(NUM_CLASSES)
print(f"Total layers: {len(model_res.layers)}")
print(f"Trainable   : {len([l for l in model_res.layers if l.trainable])}")

model_res.compile(optimizer=Adam(1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

h1_res = model_res.fit(
    train_gen_res, epochs=10, validation_data=valid_gen_res,
    callbacks=[
        ModelCheckpoint('best_phase1_res.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 1 best val accuracy: {max(h1_res.history['val_accuracy']):.4f}")

base_res.trainable = True
for layer in base_res.layers[:-30]:
    layer.trainable = False

model_res.compile(optimizer=Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

h2_res = model_res.fit(
    train_gen_res, epochs=20, validation_data=valid_gen_res,
    callbacks=[
        EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
        ModelCheckpoint('best_res.keras', monitor='val_accuracy', save_best_only=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, verbose=1)
    ], verbose=1)

print(f"Phase 2 best val accuracy: {max(h2_res.history['val_accuracy']):.4f}")

model_res.load_weights('best_res.keras')
loss, acc = model_res.evaluate(test_gen_res, verbose=1)
print(f"ResNet-50 Test Accuracy: {acc*100:.2f}%")

test_gen_res.reset()
y_pred_res = np.argmax(model_res.predict(test_gen_res, verbose=1), axis=1)
y_true_res = test_gen_res.classes
print(classification_report(y_true_res, y_pred_res, target_names=class_names_res))

model_res.save('resnet50_v2.keras')
model_res.save('/content/drive/MyDrive/resnet50_v2.keras')
print("ResNet-50 saved!")

from tensorflow.keras.models import load_model

model_eff = load_model('/content/drive/MyDrive/efficientnetb0_v2.keras', compile=False)
model_mob = load_model('/content/drive/MyDrive/mobilenetv2_v2.keras', compile=False)
model_res = load_model('/content/drive/MyDrive/resnet50_v2.keras', compile=False)

print("All 3 models loaded successfully!")

from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input as eff_pre
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mob_pre
from tensorflow.keras.applications.resnet50 import preprocess_input as res_pre
from google.colab import files
import numpy as np

CLASS_NAMES = ['glioma', 'meningioma', 'no_tumor', 'pituitary', 'unknown']

def predict_image(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    arr = image.img_to_array(img)

    pred_eff = model_eff.predict(np.expand_dims(eff_pre(arr.copy()), axis=0), verbose=0)[0]
    pred_mob = model_mob.predict(np.expand_dims(mob_pre(arr.copy()), axis=0), verbose=0)[0]
    pred_res = model_res.predict(np.expand_dims(res_pre(arr.copy()), axis=0), verbose=0)[0]

    ensemble = (pred_eff + pred_mob + pred_res) / 3

    print("=" * 50)
    print(f"  EfficientNetB0 → {CLASS_NAMES[np.argmax(pred_eff)]:12s} ({max(pred_eff)*100:.1f}%)")
    print(f"  MobileNetV2    → {CLASS_NAMES[np.argmax(pred_mob)]:12s} ({max(pred_mob)*100:.1f}%)")
    print(f"  ResNet50       → {CLASS_NAMES[np.argmax(pred_res)]:12s} ({max(pred_res)*100:.1f}%)")
    print("-" * 50)
    print(f"  ENSEMBLE       → {CLASS_NAMES[np.argmax(ensemble)]:12s} ({max(ensemble)*100:.1f}%)")
    print("=" * 50)

    if CLASS_NAMES[np.argmax(ensemble)] == 'unknown':
        print("⚠️  WARNING: This does not appear to be a brain MRI scan!")

# Upload and test
uploaded = files.upload()
for fname in uploaded:
    predict_image(fname)

from google.colab import files

files.download('/content/drive/MyDrive/efficientnetb0_v2.keras')
files.download('/content/drive/MyDrive/mobilenetv2_v2.keras')
files.download('/content/drive/MyDrive/resnet50_v2.keras')

import json
import zipfile

def fix_and_resave_v2(model_path, save_path):
    import shutil
    shutil.copy(model_path, save_path)

    with zipfile.ZipFile(save_path, 'r') as z:
        config_str = z.read('config.json').decode('utf-8')

    config_str = config_str.replace('"quantization_config": null,', '')
    config_str = config_str.replace(', "quantization_config": null', '')

    with zipfile.ZipFile(save_path, 'a') as z:
        z.writestr('config.json', config_str)

    print(f"Fixed: {save_path}")

fix_and_resave_v2('/content/drive/MyDrive/efficientnetb0_v2.keras', 'efficientnetb0_v2_fixed.keras')
fix_and_resave_v2('/content/drive/MyDrive/mobilenetv2_v2.keras',    'mobilenetv2_v2_fixed.keras')
fix_and_resave_v2('/content/drive/MyDrive/resnet50_v2.keras',       'resnet50_v2_fixed.keras')

from google.colab import files
files.download('efficientnetb0_v2_fixed.keras')
files.download('mobilenetv2_v2_fixed.keras')
files.download('resnet50_v2_fixed.keras')

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.efficientnet import preprocess_input as eff_preprocess
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mob_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as res_preprocess
from sklearn.metrics import classification_report, confusion_matrix

# Load models
model_eff = load_model('/content/drive/MyDrive/efficientnetb0_v2.keras', compile=False)
model_mob = load_model('/content/drive/MyDrive/mobilenetv2_v2.keras', compile=False)
model_res = load_model('/content/drive/MyDrive/resnet50_v2.keras', compile=False)

print("All models loaded!")

!cp "/content/drive/MyDrive/dataset (2).zip" /content/
!unzip -q /content/"dataset (2).zip" -d /content/my_dataset

# Add unknown class
from PIL import Image
os.makedirs('/content/my_dataset/dataset/test/unknown', exist_ok=True)
(_, _), (x_test, _) = tf.keras.datasets.cifar10.load_data()
for i in range(500):
    Image.fromarray(x_test[i]).resize((224,224)).save(f'/content/my_dataset/dataset/test/unknown/c_{i}.png')

TEST_DIR = '/content/my_dataset/dataset/test'
IMG_SIZE  = (224, 224)
BATCH_SIZE = 32

print("Done!")

test_gen_eff = ImageDataGenerator(preprocessing_function=eff_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)

test_gen_mob = ImageDataGenerator(preprocessing_function=mob_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)

test_gen_res = ImageDataGenerator(preprocessing_function=res_preprocess).flow_from_directory(
    TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)

class_names = [k for k, v in sorted(test_gen_eff.class_indices.items(), key=lambda x: x[1])]
print("Classes:", class_names)

# EfficientNetB0
test_gen_eff.reset()
y_pred_eff = np.argmax(model_eff.predict(test_gen_eff, verbose=1), axis=1)
y_true     = test_gen_eff.classes

# MobileNetV2
test_gen_mob.reset()
y_pred_mob = np.argmax(model_mob.predict(test_gen_mob, verbose=1), axis=1)

# ResNet50
test_gen_res.reset()
y_pred_res = np.argmax(model_res.predict(test_gen_res, verbose=1), axis=1)

print("Predictions done!")
print(f"EfficientNetB0 Accuracy: {(y_pred_eff == y_true).mean()*100:.2f}%")
print(f"MobileNetV2    Accuracy: {(y_pred_mob == y_true).mean()*100:.2f}%")
print(f"ResNet50       Accuracy: {(y_pred_res == y_true).mean()*100:.2f}%")

def plot_confusion_matrix(y_true, y_pred, class_names, model_name, filename):
    cm = confusion_matrix(y_true, y_pred)
    cm_percent = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100

    fig, axes = plt.subplots(1, 2, figsize=(18, 7))
    fig.suptitle(f'{model_name} — Confusion Matrix', fontsize=16, fontweight='bold')

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[0], annot_kws={"size": 11})
    axes[0].set_title('Counts', fontsize=13, fontweight='bold')
    axes[0].set_xlabel('Predicted Label', fontsize=11)
    axes[0].set_ylabel('True Label', fontsize=11)

    sns.heatmap(cm_percent, annot=True, fmt='.1f', cmap='Greens',
                xticklabels=class_names, yticklabels=class_names,
                linewidths=0.5, ax=axes[1], annot_kws={"size": 11})
    axes[1].set_title('Percentage (%)', fontsize=13, fontweight='bold')
    axes[1].set_xlabel('Predicted Label', fontsize=11)
    axes[1].set_ylabel('True Label', fontsize=11)

    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved: {filename}")

plot_confusion_matrix(y_true, y_pred_eff, class_names, 'EfficientNetB0', 'cm_efficientnetb0.png')

plot_confusion_matrix(y_true, y_pred_mob, class_names, 'MobileNetV2', 'cm_mobilenetv2.png')

plot_confusion_matrix(y_true, y_pred_res, class_names, 'ResNet50', 'cm_resnet50.png')

def plot_per_class_accuracy(y_true, y_pred, class_names, model_name, filename):
    cm = confusion_matrix(y_true, y_pred)
    per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100

    colors = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0', '#FF9800']
    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.bar(class_names, per_class_acc, color=colors, edgecolor='white', linewidth=1.5, width=0.5)

    for bar, acc in zip(bars, per_class_acc):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f'{acc:.2f}%', ha='center', va='bottom', fontsize=11, fontweight='bold')

    ax.set_title(f'{model_name} — Per-Class Accuracy on Test Set',
                 fontsize=14, fontweight='bold', pad=15)
    ax.set_xlabel('Class', fontsize=12)
    ax.set_ylabel('Accuracy (%)', fontsize=12)
    ax.set_ylim([0, 115])
    ax.axhline(y=np.mean(per_class_acc), color='red', linestyle='--',
               alpha=0.7, label=f'Mean: {np.mean(per_class_acc):.2f}%')
    ax.legend(fontsize=11)
    ax.grid(axis='y', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved: {filename}")

plot_per_class_accuracy(y_true, y_pred_eff, class_names, 'EfficientNetB0', 'pca_efficientnetb0.png')
plot_per_class_accuracy(y_true, y_pred_mob, class_names, 'MobileNetV2',    'pca_mobilenetv2.png')
plot_per_class_accuracy(y_true, y_pred_res, class_names, 'ResNet50',       'pca_resnet50.png')

models     = ['EfficientNetB0', 'MobileNetV2', 'ResNet-50']
accuracies = [99.39, 99.05, 99.51]
colors     = ['#2196F3', '#FF5722', '#4CAF50']

fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.bar(models, accuracies, color=colors, edgecolor='white', linewidth=1.5, width=0.4)

for bar, acc in zip(bars, accuracies):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
            f'{acc}%', ha='center', va='bottom', fontsize=13, fontweight='bold')

ax.set_title('Model Accuracy Comparison — 5 Class Brain Tumor Classification',
             fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Model', fontsize=12)
ax.set_ylabel('Test Accuracy (%)', fontsize=12)
ax.set_ylim([98, 100])
ax.axhline(y=np.mean(accuracies), color='red', linestyle='--',
           alpha=0.7, label=f'Mean: {np.mean(accuracies):.2f}%')
ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: model_comparison.png")

from google.colab import files

images_to_download = [
    'cm_efficientnetb0.png',
    'cm_mobilenetv2.png',
    'cm_resnet50.png',
    'pca_efficientnetb0.png',
    'pca_mobilenetv2.png',
    'pca_resnet50.png',
    'model_comparison.png',
]

for f in images_to_download:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
    else:
        print(f"SKIPPED: {f}")

print("All images downloaded!")

